os:
  - linux

script:
 - curl https://api.github.com/repos/frangarcj/vitasdk-buildscripts/releases  | grep browser_download_url | grep linux | head -n 1 | cut -d '"' -f 4 | xargs wget
 - tar xjf gcc-arm-vita-eabi-4_9-2015q3-20150922-linux.tar.bz2
 - export VITASDK=$PWD/gcc-arm-vita-eabi-4_9-2015q3
 - export PATH="$PATH:$VITASDK/bin"
 - git clone https://github.com/xerpi/vita_portlibs
 - chmod +x *.sh
 - ./build-vita_portlibs.sh
 - git clone https://github.com/xerpi/vita2dlib
 - ./build-vita2dlib.sh
 - ls -rls $PREFIX
env:
 global:
  - TOP=$PWD
  - PREFIX=$TOP/dist
# before_deploy:
#   - git config --global user.email "builds@travis-ci.com"
#   - git config --global user.name "Travis CI"
#   - export GIT_TAG=$TRAVIS_BRANCH-$TRAVIS_OS_NAME-0.1-v$TRAVIS_BUILD_NUMBER
#   - git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER - $TRAVIS_OS_NAME"
#   - git push -q https://$TAGPERM@github.com/frangarcj/vitasdk-buildscripts --tags
# deploy:
#   provider: releases
#   api_key: $OAUTH
#   file_glob: true
#   file: "pkg/*.tar.bz2"
#   skip_cleanup: true
#   on:
#     tags: false
#     all_branches: true
#
# branches:
#   except:
#     - /^*-v[0-9]/
